### ISSUE TITLE
Local operation is normal

### ISSUE THREAD

**Issue by Nuclear6** [fabiomatricardi/TiniLlamaGradioChat#1]
This is a great project. It is generated very quickly and takes up less than 1G of memory. Why do so few people like it?

**Comment by fabiomatricardi** [comment]
thanks, and I agree!
I contacted the guys of Gradio to tell them that their tutorial on how to use the Chat interface with models that are not OpenAI is poor.... At least here you can see how to set up your own. Thanks for your feedback
