### ISSUE TITLE
Tiny LLM in Android?

### ISSUE THREAD

**Issue by Nuclear6** [fabiomatricardi/TiniLlamaGradioChat#2]
Are there any successful cases of TinyLLM running on Android? Or do you know where there is a corresponding open source project for running llm on Android?

**Comment by fabiomatricardi** [comment]
Ciao,
you can follow the instructions on[ Llama.cpp Github page](https://github.com/ggerganov/llama.cpp)

### The section below is specifically for Android
[https://github.com/ggerganov/llama.cpp#android
](https://github.com/ggerganov/llama.cpp#android)
there may be more resources, but this one I know for certain
